# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interop_pb2 as interop__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in interop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TlsInteropWrapperStub(object):
    """--- gRPC service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadata = channel.unary_unary(
                '/tls.interop.TlsInteropWrapper/GetMetadata',
                request_serializer=interop__pb2.Empty.SerializeToString,
                response_deserializer=interop__pb2.LibraryMetadata.FromString,
                _registered_method=True)
        self.ExecuteOperation = channel.unary_unary(
                '/tls.interop.TlsInteropWrapper/ExecuteOperation',
                request_serializer=interop__pb2.OperationRequest.SerializeToString,
                response_deserializer=interop__pb2.OperationResponse.FromString,
                _registered_method=True)


class TlsInteropWrapperServicer(object):
    """--- gRPC service ---

    """

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TlsInteropWrapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=interop__pb2.Empty.FromString,
                    response_serializer=interop__pb2.LibraryMetadata.SerializeToString,
            ),
            'ExecuteOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOperation,
                    request_deserializer=interop__pb2.OperationRequest.FromString,
                    response_serializer=interop__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tls.interop.TlsInteropWrapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tls.interop.TlsInteropWrapper', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TlsInteropWrapper(object):
    """--- gRPC service ---

    """

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tls.interop.TlsInteropWrapper/GetMetadata',
            interop__pb2.Empty.SerializeToString,
            interop__pb2.LibraryMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tls.interop.TlsInteropWrapper/ExecuteOperation',
            interop__pb2.OperationRequest.SerializeToString,
            interop__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
