# OpenSSL server + OpenSSL client
services:
  server_node:
    build:
      context: ../..
      dockerfile: deploy/Dockerfile
    image: tls-interop-wrapper
    ports:
      - "50051:50051"
      - "5555:5555"
    command: ["python3", "wrapper_openssl.py"]

  client_node:
    build:
      context: ../..
      dockerfile: deploy/Dockerfile
    image: tls-interop-wrapper
    ports:
      - "50052:50051"
    command: ["python3", "wrapper_openssl.py"]

  driver:
    image: tls-interop-wrapper
    depends_on:
      - server_node
      - client_node
    environment:
      TLS_SERVER_GRPC: "server_node:50051"
      TLS_CLIENT_GRPC: "client_node:50051"
      TLS_HOSTNAME: "server_node"
    command: ["sh", "-c", "sleep 5 && PYTHONPATH=/app python3 driver.py"]
